### ISSUE TITLE
all workflows in DC/OS package throw errors about Elasticsearch URL not provided

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-workflow-agent#15]
in stdout the ascii arts keeps on repeating, in the error log i see this for every workflow:

/sbin/runsvdir started
./run: line 24: VAMP_ELASTICSEARCH_URL: not provided.

**Comment by iamtew** [comment]
Because of the missing VAMP_ELASTICSEARCH_URL confd probably couldn't expand it's configuration properly, and thus fail on its initial run, and not creating the `good2go` lock-file. This would cause the VWA service script to re-run constantly. This setting wasn't added to all the application.conf files, this has been fixed in https://github.com/magneticio/vamp-docker-images/commit/f963e4d87195bd6232b5a58b20ad6c715e3a7a7f

Also added a stderr to stdout redirect under 4e54733 to provide us (hopefully) with a bit more details if this happens in the future.
